title: Pashe.Devs
google_analytics: UA-9386106-8

disqus:
  shortname: pashe-devs

facebook_username: groups/pashe.devs
github_username:  pasheProject
rss: rss

show_excerpts: true
 
theme: minima
header_pages:
  - members/index.md
  - blog/index.md
  - connect.md
  
plugins:
  - jekyll-feed
  - jekyll-seo-tag

