title: Pashe.Devs
google_analytics: UA-9386106-8

github_username:  pasheProject
rss: rss

show_excerpts: true
 
theme: minima
header_pages:
  - members/index.md
  - blog/index.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

